//
// Generated file, do not edit! Created by opp_msgc 4.3 from packets/ccn_interest.msg.
//

#ifndef _CCN_INTEREST_M_H_
#define _CCN_INTEREST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ccnsim.h"
// }}



/**
 * Class generated from <tt>packets/ccn_interest.msg</tt> by opp_msgc.
 * <pre>
 * packet ccn_interest{
 * 	@customize(true);
 * 	abstract int path[];
 * 
 * 	chunk_t chunk; 
 * 	int hops = 0; 
 * 
 * 
 * 	int target = -1; 
 * 	int rep_target = -1; 
 * 
 * 	double btw = 0; 
 * 	int TTL = 10000; 
 * 	bool nfound = false; 
 * 
 * 	int capacity = 0;
 * 	int origin = -1; 
 * 	double Delay = 0; 
 * }
 * </pre>
 *
 * ccn_interest_Base is only useful if it gets subclassed, and ccn_interest is derived from it.
 * The minimum code to be written for ccn_interest is the following:
 *
 * <pre>
 * class ccn_interest : public ccn_interest_Base
 * {
 *   private:
 *     void copy(const ccn_interest& other) { ... }

 *   public:
 *     ccn_interest(const char *name=NULL, int kind=0) : ccn_interest_Base(name,kind) {}
 *     ccn_interest(const ccn_interest& other) : ccn_interest_Base(other) {copy(other);}
 *     ccn_interest& operator=(const ccn_interest& other) {if (this==&other) return *this; ccn_interest_Base::operator=(other); copy(other); return *this;}
 *     virtual ccn_interest *dup() const {return new ccn_interest(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from ccn_interest_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(ccn_interest);
 * </pre>
 */
class ccn_interest_Base : public ::cPacket
{
  protected:
    chunk_t chunk_var;
    int hops_var;
    int target_var;
    int rep_target_var;
    double btw_var;
    int TTL_var;
    bool nfound_var;
    int capacity_var;
    int origin_var;
    double Delay_var;

  private:
    void copy(const ccn_interest_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ccn_interest_Base&);
    // make constructors protected to avoid instantiation
    ccn_interest_Base(const char *name=NULL, int kind=0);
    ccn_interest_Base(const ccn_interest_Base& other);
    // make assignment operator protected to force the user override it
    ccn_interest_Base& operator=(const ccn_interest_Base& other);

  public:
    virtual ~ccn_interest_Base();
    virtual ccn_interest_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class ccn_interest");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setPathArraySize(unsigned int size) = 0;
    virtual unsigned int getPathArraySize() const = 0;
    virtual int getPath(unsigned int k) const = 0;
    virtual void setPath(unsigned int k, int path) = 0;
    virtual chunk_t& getChunk();
    virtual const chunk_t& getChunk() const {return const_cast<ccn_interest_Base*>(this)->getChunk();}
    virtual void setChunk(const chunk_t& chunk);
    virtual int getHops() const;
    virtual void setHops(int hops);
    virtual int getTarget() const;
    virtual void setTarget(int target);
    virtual int getRep_target() const;
    virtual void setRep_target(int rep_target);
    virtual double getBtw() const;
    virtual void setBtw(double btw);
    virtual int getTTL() const;
    virtual void setTTL(int TTL);
    virtual bool getNfound() const;
    virtual void setNfound(bool nfound);
    virtual int getCapacity() const;
    virtual void setCapacity(int capacity);
    virtual int getOrigin() const;
    virtual void setOrigin(int origin);
    virtual double getDelay() const;
    virtual void setDelay(double Delay);
};


#endif // _CCN_INTEREST_M_H_
